//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int id_event { get; set; }
        public string name_event { get; set; }
        public string description { get; set; }
        public Nullable<int> id_cell { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Cell Cell { get; set; }
    }
}
