//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Family_Tree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public History_Family_Tree()
        {
            this.List_Family_Tree = new HashSet<List_Family_Tree>();
        }
    
        public int id_history { get; set; }
        public string name_family_tree { get; set; }
        public Nullable<int> count_animal { get; set; }
        public Nullable<System.DateTime> date_start_family { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List_Family_Tree> List_Family_Tree { get; set; }
    }
}
