//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Family_Tree
    {
        public int id_list_family { get; set; }
        public Nullable<int> id_history { get; set; }
        public Nullable<int> id_animal_father { get; set; }
        public Nullable<int> id_animal_mother { get; set; }
        public Nullable<int> id_animal_child { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Animal Animal1 { get; set; }
        public virtual Animal Animal2 { get; set; }
        public virtual History_Family_Tree History_Family_Tree { get; set; }
    }
}
