//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_History
    {
        public int id_med_history { get; set; }
        public Nullable<int> id_medcard { get; set; }
        public string condition { get; set; }
        public string description { get; set; }
        public System.DateTime date_start_heal { get; set; }
        public Nullable<System.DateTime> date_end_heal { get; set; }
        public Nullable<int> id_med_procedure { get; set; }
        public Nullable<int> id_employee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Med_Procedure Med_Procedure { get; set; }
        public virtual MedCard MedCard { get; set; }
    }
}
