//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Finance
    {
        public int id_report_finance { get; set; }
        public Nullable<int> id_history_traffic { get; set; }
        public string profit { get; set; }
    
        public virtual History_Traffic History_Traffic { get; set; }
    }
}
