//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoo.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id_user { get; set; }
        public string name { get; set; }
        public string login { get; set; }
        public Nullable<int> id_role { get; set; }
        public Nullable<int> count_visit { get; set; }
    
        public virtual Login Login1 { get; set; }
        public virtual role role { get; set; }
    }
}
